name: gosql
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11, 1.12, 1.13]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Init Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS db1;'
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS db2;'

      - name: Test
        env:
          MYSQL_TEST_DSN1: "root:root@tcp(127.0.0.1:3306)/db1?parseTime=true"
          MYSQL_TEST_DSN2: "root:root@tcp(127.0.0.1:3306)/db2?parseTime=true"
        run: go get && go test -v ./...